{% set version = "3.0.1" %}

package:
  name: jira
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jira/jira-{{ version }}.tar.gz
  sha256: 5bd8f4199632bf91fcfb4ba25ad2226991d403923b75f7cd2b051b4571492831

build:
  noarch: python
  entry_points:
    - jirashell = jira.jirashell:main
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=41.0.0
    - setuptools-scm >=1.15.0
    - setuptools_scm_git_archive >=1.0
    - wheel

  run:
    - defusedxml
    - keyring
    - python >=3.6
    - requests >=2.10.0
    - requests-oauthlib >=1.1.0
    - requests-toolbelt
    - setuptools >=20.10.1

test:
  requires:
    - pip
  imports:
    - jira
  commands:
    - pip check
    - jirashell --help

about:
  home: https://github.com/pycontribs/jira
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Python library for interacting with JIRA via REST APIs.
  dev_url: https://github.com/pycontribs/jira
  doc_url: https://jira.readthedocs.io
  description: |-
    This library eases the use of the Jira REST API from Python and it has been 
    used in production for years.

extra:
  recipe-maintainers:
    - ericdill
    - parente
    - pmlandwehr
    - bollwyvl
