{% set version = "3.8.0" %}

# handle undefined PYTHON in `noarch: generic` outputs
{% if PYTHON is not defined %}{% set PYTHON = "$PYTHON" %}{% endif %}

package:
  name: jira-split
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jira/jira-{{ version }}.tar.gz
  sha256: 63719c529a570aaa01c3373dbb5a104dab70381c5be447f6c27f997302fa335a

build:
  noarch: python
  number: 0

outputs:
  - name: jira-base
    build:
      noarch: python
      script:
        - {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
      entry_points:
        - jirashell = jira.jirashell:main
    requirements:
      host:
        - pip
        - python >=3.8
        - setuptools >=60.0.0
        - setuptools-scm >=7.0.0
      run:
        - defusedxml
        - packaging
        - pillow >=2.1.0
        - python >=3.8
        - requests >=2.10.0
        - requests-oauthlib >=1.1.0
        - requests-toolbelt
        - typing_extensions >=3.7.4.2
      run_constrained:
        # see `jira-with-cli`
        - ipython >=4.0.0
        # see `jira-with-async`
        - requests-futures >=0.9.7
    test:
      requires:
        - pip
      imports:
        - jira
      commands:
        - pip check
        - jirashell --version
        - jirashell --help

  - name: jira-with-cli
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("jira-base", exact=True) }}
        - keyring
        - ipython
    test:
      requires:
        - pip
      imports:
        - jira
      commands:
        - pip check
        - jirashell --version
        - jirashell --help

  - name: jira-with-async
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("jira-base", exact=True) }}
        - requests-futures
    test:
      requires:
        - pip
      imports:
        - jira
      commands:
        - pip check

  - name: jira
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("jira-base", exact=True) }}
        - {{ pin_subpackage("jira-with-cli", exact=True) }}
    test:
      requires:
        - pip
      imports:
        - jira
      commands:
        - pip check
        - jirashell --version
        - jirashell --help

about:
  home: https://github.com/pycontribs/jira
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Python library for interacting with JIRA via REST APIs.
  dev_url: https://github.com/pycontribs/jira
  doc_url: https://jira.readthedocs.io
  description: |-
    This library eases the use of the Jira REST API from Python and it has been
    used in production for years.

extra:
  feedstock-name: jira
  recipe-maintainers:
    - ericdill
    - parente
    - bollwyvl
