{% set name = "jira" %}
{% set version = "3.0.1" %}
{% set bundle = "tar.gz" %}
{% set hash_val = "5bd8f4199632bf91fcfb4ba25ad2226991d403923b75f7cd2b051b4571492831" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash_val }}

build:
  noarch: python
  entry_points:
    - jirashell = jira.jirashell:main
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - pbr >=3.0
    - setuptools >=17.1
    - pytest-runner
    - sphinx >=1.6.5

  run:
    - python
    - defusedxml
    - pbr >=3.0.0
    - requests-oauthlib >=0.6.1
    - requests >=2.10.0
    - requests-toolbelt
    - setuptools >=20.10.1
    - six >=1.10.0

test:
  imports:
    - jira

about:
  home: https://github.com/pycontribs/jira
  license: BSD 2-Clause
  license_file: LICENSE
  summary: The easiest way to automate JIRA
  dev_url: https://github.com/pycontribs/jira
  doc_url: https://jira.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - ericdill
    - parente
    - pmlandwehr
