{% set version = "3.4.1" %}

package:
  name: jira
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jira/jira-{{ version }}.tar.gz
  sha256: 20e2df51cc686f663034543c4dec65783e9c721de6448b433d659d5c95b01c7b

build:
  noarch: python
  entry_points:
    - jirashell = jira.jirashell:main
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=41.0.0
    - setuptools-scm >=1.15.0
    - setuptools_scm_git_archive >=1.0
    - wheel

  run:
    - defusedxml
    - keyring
    - packaging
    - python >=3.8
    - requests >=2.10.0
    - requests-oauthlib >=1.1.0
    - requests-toolbelt
    - typing_extensions >=3.7.4.2

test:
  requires:
    - pip
  imports:
    - jira
  commands:
    - pip check
    - jirashell --help

about:
  home: https://github.com/pycontribs/jira
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Python library for interacting with JIRA via REST APIs.
  dev_url: https://github.com/pycontribs/jira
  doc_url: https://jira.readthedocs.io
  description: |-
    This library eases the use of the Jira REST API from Python and it has been 
    used in production for years.

extra:
  recipe-maintainers:
    - ericdill
    - parente
    - bollwyvl
